/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServersRouteImport } from './routes/servers'
import { Route as InstancesRouteImport } from './routes/instances'
import { Route as FilesRouteImport } from './routes/files'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppPromptsRouteImport } from './routes/_app/prompts'
import { Route as AppPinnedRouteImport } from './routes/_app/pinned'
import { Route as AppPerformanceRouteImport } from './routes/_app/performance'
import { Route as AppLiveMessagesRouteImport } from './routes/_app/live-messages'
import { Route as AppDocsRouteImport } from './routes/_app/docs'
import { Route as AppDiffRouteImport } from './routes/_app/diff'
import { Route as AppSessionNewRouteImport } from './routes/_app/session/new'
import { Route as AppSessionIdRouteImport } from './routes/_app/session/$id'

const ServersRoute = ServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => rootRouteImport,
} as any)
const InstancesRoute = InstancesRouteImport.update({
  id: '/instances',
  path: '/instances',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPromptsRoute = AppPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => AppRoute,
} as any)
const AppPinnedRoute = AppPinnedRouteImport.update({
  id: '/pinned',
  path: '/pinned',
  getParentRoute: () => AppRoute,
} as any)
const AppPerformanceRoute = AppPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AppRoute,
} as any)
const AppLiveMessagesRoute = AppLiveMessagesRouteImport.update({
  id: '/live-messages',
  path: '/live-messages',
  getParentRoute: () => AppRoute,
} as any)
const AppDocsRoute = AppDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AppRoute,
} as any)
const AppDiffRoute = AppDiffRouteImport.update({
  id: '/diff',
  path: '/diff',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionNewRoute = AppSessionNewRouteImport.update({
  id: '/session/new',
  path: '/session/new',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionIdRoute = AppSessionIdRouteImport.update({
  id: '/session/$id',
  path: '/session/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/about': typeof AboutRoute
  '/files': typeof FilesRoute
  '/instances': typeof InstancesRoute
  '/servers': typeof ServersRoute
  '/diff': typeof AppDiffRoute
  '/docs': typeof AppDocsRoute
  '/live-messages': typeof AppLiveMessagesRoute
  '/performance': typeof AppPerformanceRoute
  '/pinned': typeof AppPinnedRoute
  '/prompts': typeof AppPromptsRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
  '/session/$id': typeof AppSessionIdRoute
  '/session/new': typeof AppSessionNewRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/files': typeof FilesRoute
  '/instances': typeof InstancesRoute
  '/servers': typeof ServersRoute
  '/diff': typeof AppDiffRoute
  '/docs': typeof AppDocsRoute
  '/live-messages': typeof AppLiveMessagesRoute
  '/performance': typeof AppPerformanceRoute
  '/pinned': typeof AppPinnedRoute
  '/prompts': typeof AppPromptsRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
  '/session/$id': typeof AppSessionIdRoute
  '/session/new': typeof AppSessionNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/about': typeof AboutRoute
  '/files': typeof FilesRoute
  '/instances': typeof InstancesRoute
  '/servers': typeof ServersRoute
  '/_app/diff': typeof AppDiffRoute
  '/_app/docs': typeof AppDocsRoute
  '/_app/live-messages': typeof AppLiveMessagesRoute
  '/_app/performance': typeof AppPerformanceRoute
  '/_app/pinned': typeof AppPinnedRoute
  '/_app/prompts': typeof AppPromptsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/session/$id': typeof AppSessionIdRoute
  '/_app/session/new': typeof AppSessionNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about'
    | '/files'
    | '/instances'
    | '/servers'
    | '/diff'
    | '/docs'
    | '/live-messages'
    | '/performance'
    | '/pinned'
    | '/prompts'
    | '/settings'
    | '/'
    | '/session/$id'
    | '/session/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/files'
    | '/instances'
    | '/servers'
    | '/diff'
    | '/docs'
    | '/live-messages'
    | '/performance'
    | '/pinned'
    | '/prompts'
    | '/settings'
    | '/'
    | '/session/$id'
    | '/session/new'
  id:
    | '__root__'
    | '/_app'
    | '/about'
    | '/files'
    | '/instances'
    | '/servers'
    | '/_app/diff'
    | '/_app/docs'
    | '/_app/live-messages'
    | '/_app/performance'
    | '/_app/pinned'
    | '/_app/prompts'
    | '/_app/settings'
    | '/_app/'
    | '/_app/session/$id'
    | '/_app/session/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AboutRoute: typeof AboutRoute
  FilesRoute: typeof FilesRoute
  InstancesRoute: typeof InstancesRoute
  ServersRoute: typeof ServersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servers': {
      id: '/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof ServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instances': {
      id: '/instances'
      path: '/instances'
      fullPath: '/instances'
      preLoaderRoute: typeof InstancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/prompts': {
      id: '/_app/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof AppPromptsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pinned': {
      id: '/_app/pinned'
      path: '/pinned'
      fullPath: '/pinned'
      preLoaderRoute: typeof AppPinnedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/performance': {
      id: '/_app/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AppPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/live-messages': {
      id: '/_app/live-messages'
      path: '/live-messages'
      fullPath: '/live-messages'
      preLoaderRoute: typeof AppLiveMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/docs': {
      id: '/_app/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof AppDocsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/diff': {
      id: '/_app/diff'
      path: '/diff'
      fullPath: '/diff'
      preLoaderRoute: typeof AppDiffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/session/new': {
      id: '/_app/session/new'
      path: '/session/new'
      fullPath: '/session/new'
      preLoaderRoute: typeof AppSessionNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/session/$id': {
      id: '/_app/session/$id'
      path: '/session/$id'
      fullPath: '/session/$id'
      preLoaderRoute: typeof AppSessionIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDiffRoute: typeof AppDiffRoute
  AppDocsRoute: typeof AppDocsRoute
  AppLiveMessagesRoute: typeof AppLiveMessagesRoute
  AppPerformanceRoute: typeof AppPerformanceRoute
  AppPinnedRoute: typeof AppPinnedRoute
  AppPromptsRoute: typeof AppPromptsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSessionIdRoute: typeof AppSessionIdRoute
  AppSessionNewRoute: typeof AppSessionNewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDiffRoute: AppDiffRoute,
  AppDocsRoute: AppDocsRoute,
  AppLiveMessagesRoute: AppLiveMessagesRoute,
  AppPerformanceRoute: AppPerformanceRoute,
  AppPinnedRoute: AppPinnedRoute,
  AppPromptsRoute: AppPromptsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppSessionIdRoute: AppSessionIdRoute,
  AppSessionNewRoute: AppSessionNewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AboutRoute: AboutRoute,
  FilesRoute: FilesRoute,
  InstancesRoute: InstancesRoute,
  ServersRoute: ServersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
